In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../input/train.csv')
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [2]:
def get_words_res(df,k,v=False,low=False):
    tmp_df = df.copy()
    if low is False:
        tmp_df['flag'] = tmp_df['comment_text'].apply(lambda x:k in x)
    else:
        tmp_df['flag'] = tmp_df['comment_text'].apply(lambda x:k.lower() in x.lower())
    tmp_df = tmp_df[tmp_df.flag == True]
    if v is True:
        #print(tmp_df.head())
        #print(tmp_df.describe())
        pass
    common_y = tmp_df[['toxic','severe_toxic','obscene','threat','insult','identity_hate']].mean().values
    return common_y,len(tmp_df)

common_y,data_cnt = get_words_res(df,'COCKSUCK',True,False)
print(common_y,data_cnt)

[1.         0.61904762 1.         0.         1.         0.23809524] 21


In [3]:
common_y,data_cnt = get_words_res(df,'MOTHJER FUCKER',True, True)
print(common_y,data_cnt)

[1. 1. 1. 0. 1. 0.] 5


In [4]:
common_y,data_cnt = get_words_res(df,'NIGGERS',True,False)
print(common_y,data_cnt)

[1.         0.28571429 0.57142857 0.14285714 0.71428571 1.        ] 7


In [5]:
common_y,data_cnt = get_words_res(df,'You faggot',True,True)
print(common_y,data_cnt)

[1.         0.30769231 0.92307692 0.09615385 0.92307692 0.46153846] 52


In [6]:
common_y,data_cnt = get_words_res(df,'you suck dick',True,True)
print(common_y,data_cnt)

[1.  0.4 1.  0.1 0.9 0.1] 10


In [7]:
common_y,data_cnt = get_words_res(df,'fuck fuck',True,True)
print(common_y,data_cnt)

[1.         0.41176471 1.         0.         0.64705882 0.05882353] 17


In [8]:
common_y,data_cnt = get_words_res(df,'fuck you asshole',True,True)
print(common_y,data_cnt)

[1.     0.75   1.     0.0625 0.875  0.0625] 16


In [9]:
common_y,data_cnt = get_words_res(df,'uck bitch',True,True)
print(common_y,data_cnt)

[1.         0.16666667 1.         0.         1.         0.        ] 6


In [10]:
common_y,data_cnt = get_words_res(df,'gaybo',True,True)
print(common_y,data_cnt)

[1.  0.2 0.8 0.  1.  0.6] 5


In [11]:
common_y,data_cnt = get_words_res(df,'son of bitch',True,True)
print(common_y,data_cnt)

[1.   0.25 1.   0.   0.75 0.25] 8


In [12]:
common_y,data_cnt = get_words_res(df,'fuck off yo',True,True)
print(common_y,data_cnt)

[1.         0.44642857 0.98214286 0.03571429 0.92857143 0.14285714] 56


In [13]:
common_y,data_cnt = get_words_res(df,'pile of shit',True,True)
print(common_y,data_cnt)

[1.         0.25       0.83333333 0.         0.5        0.08333333] 12


In [14]:
common_y,data_cnt = get_words_res(df,'niggas',True,True)
print(common_y,data_cnt)

[1.         0.41666667 0.91666667 0.         0.91666667 0.75      ] 12


In [15]:
common_y,data_cnt = get_words_res(df,'cunts like you',True,True)
print(common_y,data_cnt)

[1.         0.14285714 0.57142857 0.         0.71428571 0.        ] 7


In [16]:
common_y,data_cnt = get_words_res(df,'shitfuck',True,True)
print(common_y,data_cnt)

[1.         0.66666667 1.         0.         1.         0.        ] 3


In [17]:
common_y,data_cnt = get_words_res(df,'fggt',True,True)
print(common_y,data_cnt)

[1.         0.         0.5        0.         0.66666667 0.        ] 6


In [18]:
low_correct_dict = {
    'fggt':[1,0,0,0,0,0],
    'shitfuck':[1,0,0,0,0,0],
    'MOTHJER FUCKER':[1,1,1,0,1,0],
    'niggas':[1,0,0,0,0,0],
    'cunts like you':[1,0,0,0,0,0],
    'pile of shit':[1,0,0,0,0,0],
    'fuck off yo':[1,0,0,0,0,0],
    'son of bitch':[1,0,1,0,0,0],
    'gaybo':[1,0,0,0,1,0],
    'uck bitch':[1,0,1,0,1,0],
    'fuck you asshole':[1,0,1,0,0,0],
    'You faggot':[1,0,0,0,0,0],
    'you suck dick':[1,0,1,0,0,0],
    'fuck fuck':[1,0,1,0,0,0],
}
same_correct_dict = {
    'COCKSUCK':[1,0,1,0,1,0],
    'NIGGERS':[1,0,0,0,0,1]
}

In [19]:
# post process on sub
test_df = pd.read_csv('../input/test.csv')
curr_best_sub = pd.read_csv('../results/weighted_9873.csv.gz')
test_df.head()

id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [20]:
curr_best_sub.head()

id     toxic  severe_toxic   obscene    threat    insult  \
0  00001cee341fdb12  0.970936      0.377895  0.952810  0.155500  0.902028   
1  0000247867823ef7  0.027330      0.027189  0.026810  0.026725  0.027590   
2  00013b17ad220c46  0.029014      0.026818  0.027590  0.026985  0.027381   
3  00017563c3f7919a  0.026348      0.026814  0.026509  0.027018  0.026950   
4  00017695ad8997eb  0.030407      0.026804  0.027234  0.027047  0.027885   

   identity_hate  
0       0.420624  
1       0.027318  
2       0.026945  
3       0.026926  
4       0.027215

In [21]:
test_data = test_df['comment_text'].values
y_out = curr_best_sub.values[:,1:]
print(test_data[0])
print(y_out[:5])

Yo bitch Ja Rule is more succesful then you'll ever be whats up with you and hating you sad mofuckas...i should bitch slap ur pethedic white faces and get you to kiss my ass you guys sicken me. Ja rule is about pride in da music man. dont diss that shit on him. and nothin is wrong bein like tupac he was a brother too...fuckin white boys get things right next time.,
[[0.9709359406923872 0.3778954024694011 0.9528100896367936
  0.15550044047291572 0.9020275094472155 0.42062445455584135]
 [0.027329612593034184 0.0271893440232196 0.026809520673438347
  0.026725202638426458 0.0275895438874506 0.027318162720011058]
 [0.029014192130255183 0.02681797145124772 0.027589894020214285
  0.026985403821949548 0.027380554719235516 0.02694450344850871]
 [0.0263479879949147 0.02681393227541701 0.026508704553109236
  0.027017705140637283 0.02694985767396449 0.02692608528778193]
 [0.030406639177652593 0.026804393090793525 0.02723383693280946
  0.027047127303501017 0.02788471438012103 0.02721488401283934]]


In [22]:
for idx,t in enumerate(test_data):
    for k in low_correct_dict:
        if k.lower() in t.lower():
            print(t)
            old_y = y_out[idx].copy()
            new_res = low_correct_dict[k]
            changed_flag = False
            for j in range(6):
                if new_res[j] == 1:
                    if y_out[idx][j] > 0.5: # update
                        changed_flag = True
                        y_out[idx][j] = min(0.9999,y_out[idx][j]*1.2)
            if changed_flag:
                print(old_y)
                print(y_out[idx])
            print('--------------------')

FUCK YOU YOU LIKE ANGELIQUE CARRINGTON AND TAMARA HARRINGTON??????FUCK YOU ASSHOLE!!!!!!
[0.9708430015397568 0.5884218560118735 0.9688288063645298
 0.03140144216353169 0.9350374899918464 0.0692000946707977]
[0.9999 0.5884218560118735 0.9999 0.03140144216353169 0.9350374899918464
 0.0692000946707977]
--------------------
How does it feel now you faggot
[0.9508417501845532 0.08442437629528843 0.7579465401340146
 0.029634347033128613 0.8021924226286568 0.3708733728161221]
[0.9999 0.08442437629528843 0.7579465401340146 0.029634347033128613
 0.8021924226286568 0.3708733728161221]
--------------------
" 

 To the person who said: ""WHAT THE FUCK BITCH, STOP BLOCKINMG ME OR ILL KICK YOUR FUCK ASS!!!!!!!!!!!!!!!!!!!!!!!!!!!!'"" - Never say that to an admin. You need to learn respect for others.  "
[0.9700673309392815 0.3693251348612912 0.9638232339312982
 0.12251632432320116 0.8670166234005094 0.05355039600220382]
[0.9999 0.3693251348612912 0.9999 0.12251632432320116 0.9999
 0.0535503960022038

Philoso    fuck bitches get money phy
[0.9745193473810744 0.4720806930815902 0.9727097130238926
 0.028922974431904936 0.8984167364180127 0.14018009364020415]
[0.9999 0.4720806930815902 0.9999 0.028922974431904936 0.9999
 0.14018009364020415]
--------------------
==buzon23== 
 You are a son of bitch!!!
[0.9686572598686654 0.2674136244552418 0.9533298894194552
 0.030321332622239107 0.9287755975888249 0.06398125442453617]
[0.9999 0.2674136244552418 0.9999 0.030321332622239107 0.9287755975888249
 0.06398125442453617]
--------------------
fuck fuck fuck fuck fuck
[0.9727406377280524 0.5790383667010948 0.9731091273311162
 0.028695054345113408 0.6334751712598983 0.04927445800788538]
[0.9999 0.5790383667010948 0.9999 0.028695054345113408 0.6334751712598983
 0.04927445800788538]
--------------------
fuck off you dickhead and what kind of name is squeakbox anyway,change it fast or you die.
[0.9717351735646859 0.4530748412554583 0.9656232615008388
 0.3319596128494366 0.9130947105451704 0.04921254

==GIBALDI== 
 HIS NAME WAS GIBALDI YOU FAGGOT, DONT EVER CHANGE IT AGAIN
[0.9474872800228836 0.09795377762607634 0.7290126170930061
 0.03006287375511535 0.7927274637876232 0.3372193297398149]
[0.9999 0.09795377762607634 0.7290126170930061 0.03006287375511535
 0.7927274637876232 0.3372193297398149]
--------------------
Keep vandalising my niggas!!!
[0.9029944755662916 0.08565590807914374 0.6045839114968341
 0.02955720264778945 0.5595062160696807 0.5572276290745795]
[0.9999 0.08565590807914374 0.6045839114968341 0.02955720264778945
 0.5595062160696807 0.5572276290745795]
--------------------
== fuck off you shill == 

 just hicks puppet aren't you sad fucking shill cunt
[0.9757590703209886 0.5032140603823827 0.973472071709436
 0.0334302785383452 0.9424578160730746 0.1034917156426006]
[0.9999 0.5032140603823827 0.973472071709436 0.0334302785383452
 0.9424578160730746 0.1034917156426006]
--------------------
== Quick question == 

 Just wanted to let you know that you haven't gotten rid of

==You Cunt == 
 Go fuck yourself you piece of shit. Don't make me tea beg your mama you faggot!!!
[0.9759275888737988 0.5940937756352217 0.9712901616924936
 0.04799174042065072 0.9389214726144772 0.5138730334239979]
[0.9999 0.5940937756352217 0.9712901616924936 0.04799174042065072
 0.9389214726144772 0.5138730334239979]
--------------------
== Da Realist (Roc) == 

 Da Realist is one gay ass nigga Name Roc who spends his time on facebook trying to fuck niggas....he is a child molester an loves underage Boys... 

 He Lives in statesboro,ga 

 links to his page 

     * Log On With Caution* 

 http://www.facebook.com/profile.php?id=540150553#!/profile.php?id=100000598720561 

 for any gay dude that wanna talk to him get at him his number 912 618 3771 

 Hehe you my boi doe man LMAO srry
[0.9539929796779374 0.1676466741582062 0.8675930973518422
 0.032983444061756136 0.7981650079464117 0.7607691667008505]
[0.9999 0.1676466741582062 0.8675930973518422 0.032983444061756136
 0.798165007946411

" 

 == About your edit concerning Nick Jr UK. == 

 On Thursday 10 July, you have vandalized Nick Jr UK's article on Wikipedia. 

 Your edit to vandalism of that article looks like this: ""Are you ready to jump my niggas?! Turn the fucking bass up right now!!!!!!"" 

 You have an obsession to one of the currently aired programmes on Nick Jr called ""Poppy Cat"" 

 This need to STOP immediately, otherwise you WILL be facing a BLOCK  
 to your account. 

 I'm not laughing with you, man. 

 JG 

   "
[0.8425618419535006 0.050928414527512345 0.6534946980131408
 0.03859764110240897 0.42750295531760496 0.17910686076690038]
[0.9999 0.050928414527512345 0.6534946980131408 0.03859764110240897
 0.42750295531760496 0.17910686076690038]
--------------------
fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck
[0.9724716727953546 0.5988166968543175 0.9726715977720456
 0.028635294418000518 0.6123883952243407 0.048820236009211364]
[0.9999 0.5988166968543175 0.9999 0.028635294418000518 0.612388395224340

== Heck With You == 

 Fuck you asshole!
[0.9740202420915294 0.4542470964199802 0.9721931410157932
 0.03087701773779432 0.9375686107367032 0.044795598117747255]
[0.9999 0.4542470964199802 0.9999 0.03087701773779432 0.9375686107367032
 0.044795598117747255]
--------------------
I Can design of Wikipedia we are copy things from the web Today! You Son of Bitch!
[0.9051705636220732 0.06458943955698633 0.8305392250211274
 0.028980072200245326 0.7644301278618605 0.036760882671831724]
[0.9999 0.06458943955698633 0.9966470700253529 0.028980072200245326
 0.7644301278618605 0.036760882671831724]
--------------------
Fuck you asshole, you don't even know why I did it.
[0.9715440882623554 0.4376983199518385 0.9696427664540872
 0.031085657147645294 0.9240745332029132 0.04002572644591107]
[0.9999 0.4376983199518385 0.9999 0.031085657147645294 0.9240745332029132
 0.04002572644591107]
--------------------
fuck off you little queer.
[0.972953320137524 0.4219194293224218 0.9680178268335992
 0.0321465546

[0.9999 0.05812215346175719 0.6484792290179756 0.03018862040104106
 0.6617739625418254 0.25978385788329184]
--------------------
"[2Pac talking] 
 (""Fuck Jay-Z"") 
 What's up niggas, ay yo, I know you ain't talking 'bout me dog 
 You, what? 
 (""Fuck Jay-Z"") 
 You been on my dick nigga, you love my style, nigga 
 (""Fuck Jay-Z"") 

 [Chorus] 
 (I) Fuck with your soul like ether 
 (Will) Teach you the king you know you 
 (Not) ""God's son"" across the belly 
 (Lose) I prove you lost already 

 Brace yourself for the main event 
 Y'all impatiently waiting 
 It's like an AIDS test, what's the results? 
 Not positive, who's the best? Pac, Nas and Big 
 Ain't no best, East, West, North, South, flossed out, greedy 
 I embrace y'all with napalm 
 Blows up, no guts, left chest, face gone 
 How could Nas be garbage? 
 Semi-autos at your cartilage 
 Burner at the side of your dome, come outta my throne 
 I got this, locked since '9-1 
 I am the truest, name a rapper that I ain't influenced 
 G

== GAY == 

 YOUR A WANKEST WANKEST WANKEST WANKEST WANKEST WANKEST WANKEST WANKEST WANKEST FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK TRAMP TRAMP TRAMP TRAMP TRAMP TRAMP TRAMP GAY GAY GAY GAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[0.974082168386047 0.5965327220633263 0.9633598983988452
 0.034966436157249765 0.9147358827921112 0.8330699202439524]
[0.9999 0.5965327220633263 0.9999 0.034966436157249765 0.9147358827921112
 0.8330699202439524]
--------------------
" 

 == Citation needed == 

 ""At Woodstock in 1969, Hoffman interrupted The Who's performance to attempt a protest speech against the jailing of John Sinclair of the White Panther Party. He grabbed a microphone and yelled, ""I think this is a pile of shit! While John Sinclair rots in prison ..."". The Who's guitarist, Pete Townshend, unhappy with the interruption, cut Hoffman off mid-sentence, snarling, ""Fuck off! Fuck off my fucking stage!"" He then struck Hoffman with his guitar, sending him tumbling o

==London Gangs Aren't Serious== 
 Gang members in London, UK? I've seen videos about London Gangs, these british gangs are copying American gang cultures, these packs of opps claimed they're very tough and claimed London isn't a game at all, these niggas aren't too serious, they're corny and a friggin' huge joke. They don't look gangs members to me in my opinion, they don't sag their pants and place a bandana at the top on their heads. These niggas all look very stupid for some apparent reasons and some british niggas said Americans are pussies, they're one huge pussies in the universe.
[0.7552611399672748 0.0469119304990287 0.5429121393481195
 0.02786122225385289 0.5386171742476592 0.4754160133553973]
[0.9063133679607298 0.0469119304990287 0.5429121393481195
 0.02786122225385289 0.5386171742476592 0.4754160133553973]
--------------------
FUCKIDY FUCK FUCK FUCK!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[0.9733376367279052 0.6071113790529201 0.9734086183823364
 0.029527528768971405 0.6693222010457529

Fuck off you stupid cunt.  Wikipedia is shit for retards who still live with their moms. 

 ==Wikipedia is fucking shit== 
 Wikipedia, or 'fucking shit' as it is in English, is a fucking retarded website for retards. 

 It started off as a shit website and then developed into a shit website.  Today it is a shit website full of shit and read by retards like  (a retard who is shit, lives with his mom and still wets the bed).
[0.9768982026727696 0.5159815227327174 0.9696035653649602
 0.04017292751380265 0.9406291228295592 0.20312860005352534]
[0.9999 0.5159815227327174 0.9696035653649602 0.04017292751380265
 0.9406291228295592 0.20312860005352534]
--------------------
FUCK FUCK YOU YOU
[0.9743418811481588 0.6328748361910207 0.9739819127506572
 0.03220567034415131 0.8779328273203039 0.051662296445170036]
[0.9999 0.6328748361910207 0.9999 0.03220567034415131 0.8779328273203039
 0.051662296445170036]
--------------------
"GET A FUCKING LIFE   FUCK FUCK FUCK FUCK FUCK ASS ASS ASS DICK DICK DI

== Stop it you faggot. == 

 Don't say rap is crap fag boy.
[0.9762444181783896 0.17391875117151995 0.8837963380387017
 0.033232642061872715 0.8907243533048141 0.5002849906873529]
[0.9999 0.17391875117151995 0.8837963380387017 0.033232642061872715
 0.8907243533048141 0.5002849906873529]
--------------------
== FUCK == 
 FUCK FUCK FUCK
[0.9728586516490028 0.6098317319175066 0.973003457152554
 0.028638856934255982 0.637366714682947 0.04903257335731838]
[0.9999 0.6098317319175066 0.9999 0.028638856934255982 0.637366714682947
 0.04903257335731838]
--------------------
SHUT THE FUCK UP YOU BITCH ASS NIGGAS WHO SUCK PUSSY & DICK EVERYDAY LMAO
[0.9782761278359764 0.6834830518141914 0.9736966593719696
 0.038737571738890614 0.947961893338376 0.6519733182598363]
[0.9999 0.6834830518141914 0.9736966593719696 0.038737571738890614
 0.947961893338376 0.6519733182598363]
--------------------
" 

 :In other words, you are making this horseshit up as you go.  When and where did Colonel Hackworth say th

" 

 GOODKARMA ""Bonadea has never been less than exemplary""?!!! Are you joking or what? And who are you anyway? His lawyer? Please and I ask you this kindly read my comments again. I cannot dissociate content from contributors when one of the contributors is treating my work (and hence my person) like a pile of shit! I trust you understand... Regards. Bcd3174."
--------------------
ayo buddy i enjoy vandilyzing wikipedia so fuck bitch
[0.9691322584721154 0.2691518090347001 0.9650474600843988
 0.029489783733537105 0.8681802594999961 0.08389232815139712]
[0.9999 0.2691518090347001 0.9999 0.029489783733537105 0.9999
 0.08389232815139712]
--------------------
make's you not want to shit ever agin or it make's you suck dick!
[0.9718410568260568 0.2732279155651065 0.9544151792525112
 0.03005451795463018 0.854394405685955 0.046716285101277344]
[0.9999 0.2732279155651065 0.9999 0.03005451795463018 0.854394405685955
 0.046716285101277344]
--------------------
== Oi Dickhead == 
 Get the fuck 

I see that you two are sick individuals hell bent on spearding your propaganda.  You faggots(it's in the wikipedia) need to stop it.  No matter what you do on here, CT IS IN the NY/NJ/CT Tri-state area.  That is how we view ourselves and that is the reality.
[0.8360363551307165 0.04355679942206343 0.4890750672471368
 0.02853738388566807 0.5672835452222227 0.1953898554035499]
[0.9999 0.04355679942206343 0.4890750672471368 0.02853738388566807
 0.5672835452222227 0.1953898554035499]
--------------------
::::Excuse me, Your Biased Majesty, but “You’re going to be dumping your comrades’ bodies soon, you faggot, where we only bury stray dogs. And that’s where you are soon going to join them.” Of course they bury the enemy dead with all due military respect, yes sir. Just like they treat prisoners of war just like they should, and the civilian hostages... oh wait, they should not take hostages at all.
[0.8032522661744455 0.05407660932422775 0.44152400855402346
 0.12484661041535945 0.581285216

*Exactly, she ain't messin with no '''broke niggas'', how is that saying she's dating a younger guy??
--------------------
Hennapage.com IS AN UNEMPLOYED MOTHER FUCKING BASTARD LOSER. ROTS HERE IN WIKI EVERYDAY! HE IS A LOSER IN LIFE. LOSER Hennapage.com FUCK FUCK FUCK LOSER NJGW FUCK FUCK FUCKLOSER NJGW FUCK FUCK FUCKLOSER Hennapage.com FUCK FUCK
[0.9734117073266128 0.5922153240082664 0.9680387282668624
 0.032453882300418284 0.9338505843309248 0.08486386081433793]
[0.9999 0.5922153240082664 0.9999 0.032453882300418284 0.9338505843309248
 0.08486386081433793]
--------------------
Suck a dick. Like canada disco spinster you faggot
[0.9728537742396332 0.4104457348253373 0.9620123124276304
 0.03114974254730508 0.939713533411742 0.4636002752681264]
[0.9999 0.4104457348253373 0.9620123124276304 0.03114974254730508
 0.939713533411742 0.4636002752681264]
--------------------
be ignored, hahaha, SHOVE THAT UP YOUR ASS YOU FAGGOTY ASS COWARD
[0.973327795337618 0.2994864803583554 0.9229356595035

FUCK YOU ASSHOLE ILL DDOS THE SITE
[0.974000240282996 0.6204660817579267 0.9717620737530724
 0.03489145883725203 0.9342913883262808 0.06333726605578102]
[0.9999 0.6204660817579267 0.9999 0.03489145883725203 0.9342913883262808
 0.06333726605578102]
--------------------
"You coming from Sicily and me being from Lombardy, You know how much respect i have for you and your Opinion/Authority?? ZERO, You subhuman can go F yourself, and you can have that in perfect plain Insüber(west lombard). You are not the gospel or top authority of wikipedia so dont judge my actions you sicilian scum. And do not support AC Milan, you are not Milanese so fuck off you are not welcome. DAUFER.  —Preceding unsigned comment added by   •    

  
 "
[0.9296493496156604 0.07047937571271372 0.7923412751164274
 0.029872510841297724 0.706708527226785 0.20643293170661164]
[0.9999 0.07047937571271372 0.7923412751164274 0.029872510841297724
 0.706708527226785 0.20643293170661164]
--------------------
::Well I dont give 

semen fuck bitches ass motherfucker
[0.9758219477160794 0.6267535632887921 0.9754771882664957
 0.03356064855288693 0.9264765387084511 0.1372734258442784]
[0.9999 0.6267535632887921 0.9999 0.03356064855288693 0.9999
 0.1372734258442784]
--------------------
EAT SHIT AND DIE YOU FAGGOT NAZI LOVING JEW HATING MOTHERFUCKER!!! I'LL MURDER YOU IN YOUR OWN HOME YOU FAGGOT!! I WILL FIND YOU, SLIT YOUR THROAT, DRINK YOUR BLOOD, PISS DOWN YOUR MOUTH, CUT YOUR LIVER OUT, COOK IT AND EAT IT FOR BREAKFAST, LUNCH AND DINER.  THEN I WILL FUCK YOUR MOM, DIG YOUR GRANDMOM UP FROM HER GRAVE AND FUCK HER IN HER ASS LIKE SHE COULDN'T GET IT FROM YOUR GRANDDAD.  I'LL DIG HIM UP TO, SIT HIM UP AND HE CAN WATCH ME ASS FUCK YOUR DEAD GRANNY!
[0.9782450586255672 0.6891918898310024 0.9642696027204832
 0.621361977743939 0.9402940106558368 0.7772590136032133]
[0.9999 0.6891918898310024 0.9642696027204832 0.621361977743939
 0.9402940106558368 0.7772590136032133]
--------------------
Wikipedia is communism isnt it,

In [23]:
sub = curr_best_sub.copy()
sub[['toxic','severe_toxic','obscene','threat','insult','identity_hate']] = y_out
sub.to_csv('../results/key_word_update_from_9873.csv.gz',index=False, compression='gzip')
sub.head()  # still PUB 9873, no improve

id     toxic  severe_toxic   obscene    threat    insult  \
0  00001cee341fdb12  0.970936      0.377895  0.952810  0.155500  0.902028   
1  0000247867823ef7  0.027330      0.027189  0.026810  0.026725  0.027590   
2  00013b17ad220c46  0.029014      0.026818  0.027590  0.026985  0.027381   
3  00017563c3f7919a  0.026348      0.026814  0.026509  0.027018  0.026950   
4  00017695ad8997eb  0.030407      0.026804  0.027234  0.027047  0.027885   

   identity_hate  
0       0.420624  
1       0.027318  
2       0.026945  
3       0.026926  
4       0.027215