In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../input/train.csv')
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [2]:
def get_words_res(df,k,v=False,low=False):
    tmp_df = df.copy()
    if low is False:
        tmp_df['flag'] = tmp_df['comment_text'].apply(lambda x:k in x)
    else:
        tmp_df['flag'] = tmp_df['comment_text'].apply(lambda x:k.lower() in x.lower())
    tmp_df = tmp_df[tmp_df.flag == True]
    if v is True:
        #print(tmp_df.head())
        #print(tmp_df.describe())
        pass
    common_y = tmp_df[['toxic','severe_toxic','obscene','threat','insult','identity_hate']].mean().values
    return common_y,len(tmp_df)

common_y,data_cnt = get_words_res(df,'COCKSUCK',True,False)
print(common_y,data_cnt)

[1.         0.61904762 1.         0.         1.         0.23809524] 21


In [3]:
common_y,data_cnt = get_words_res(df,'MOTHJER FUCKER',True, True)
print(common_y,data_cnt)

[1. 1. 1. 0. 1. 0.] 5


In [4]:
common_y,data_cnt = get_words_res(df,'NIGGERS',True,False)
print(common_y,data_cnt)

[1.         0.28571429 0.57142857 0.14285714 0.71428571 1.        ] 7


In [5]:
common_y,data_cnt = get_words_res(df,'You faggot',True,True)
print(common_y,data_cnt)

[1.         0.30769231 0.92307692 0.09615385 0.92307692 0.46153846] 52


In [6]:
common_y,data_cnt = get_words_res(df,'you suck dick',True,True)
print(common_y,data_cnt)

[1.  0.4 1.  0.1 0.9 0.1] 10


In [7]:
common_y,data_cnt = get_words_res(df,'fuck fuck',True,True)
print(common_y,data_cnt)

[1.         0.41176471 1.         0.         0.64705882 0.05882353] 17


In [8]:
common_y,data_cnt = get_words_res(df,'fuck you asshole',True,True)
print(common_y,data_cnt)

[1.     0.75   1.     0.0625 0.875  0.0625] 16


In [9]:
common_y,data_cnt = get_words_res(df,'uck bitch',True,True)
print(common_y,data_cnt)

[1.         0.16666667 1.         0.         1.         0.        ] 6


In [10]:
common_y,data_cnt = get_words_res(df,'gaybo',True,True)
print(common_y,data_cnt)

[1.  0.2 0.8 0.  1.  0.6] 5


In [11]:
common_y,data_cnt = get_words_res(df,'son of bitch',True,True)
print(common_y,data_cnt)

[1.   0.25 1.   0.   0.75 0.25] 8


In [12]:
common_y,data_cnt = get_words_res(df,'fuck off yo',True,True)
print(common_y,data_cnt)

[1.         0.44642857 0.98214286 0.03571429 0.92857143 0.14285714] 56


In [13]:
common_y,data_cnt = get_words_res(df,'pile of shit',True,True)
print(common_y,data_cnt)

[1.         0.25       0.83333333 0.         0.5        0.08333333] 12


In [14]:
common_y,data_cnt = get_words_res(df,'niggas',True,True)
print(common_y,data_cnt)

[1.         0.41666667 0.91666667 0.         0.91666667 0.75      ] 12


In [15]:
common_y,data_cnt = get_words_res(df,'cunts like you',True,True)
print(common_y,data_cnt)

[1.         0.14285714 0.57142857 0.         0.71428571 0.        ] 7


In [16]:
common_y,data_cnt = get_words_res(df,'shitfuck',True,True)
print(common_y,data_cnt)

[1.         0.66666667 1.         0.         1.         0.        ] 3


In [17]:
common_y,data_cnt = get_words_res(df,'fggt',True,True)
print(common_y,data_cnt)

[1.         0.         0.5        0.         0.66666667 0.        ] 6


In [18]:
low_correct_dict = {
    'fggt':[1,0,0,0,0,0],
    'shitfuck':[1,0,0,0,0,0],
    'MOTHJER FUCKER':[1,1,1,0,1,0],
    'niggas':[1,0,0,0,0,0],
    'cunts like you':[1,0,0,0,0,0],
    'pile of shit':[1,0,0,0,0,0],
    'fuck off yo':[1,0,0,0,0,0],
    'son of bitch':[1,0,1,0,0,0],
    'gaybo':[1,0,0,0,1,0],
    'uck bitch':[1,0,1,0,1,0],
    'fuck you asshole':[1,0,1,0,0,0],
    'You faggot':[1,0,0,0,0,0],
    'you suck dick':[1,0,1,0,0,0],
    'fuck fuck':[1,0,1,0,0,0],
}
same_correct_dict = {
    'COCKSUCK':[1,0,1,0,1,0],
    'NIGGERS':[1,0,0,0,0,1]
}

In [19]:
# post process on sub
test_df = pd.read_csv('../input/test.csv')
curr_best_sub = pd.read_csv('../results/weighted_avg_sub_9872.csv.gz')
test_df.head()

id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [20]:
curr_best_sub.head()

id     toxic  severe_toxic   obscene    threat    insult  \
0  00001cee341fdb12  0.981518      0.355128  0.961365  0.135401  0.906111   
1  0000247867823ef7  0.008279      0.007033  0.007163  0.006914  0.007326   
2  00013b17ad220c46  0.010245      0.007200  0.008242  0.006971  0.007609   
3  00017563c3f7919a  0.007163      0.006918  0.007063  0.006965  0.007115   
4  00017695ad8997eb  0.011148      0.006965  0.007656  0.006930  0.007924   

   identity_hate  
0       0.410450  
1       0.007097  
2       0.007179  
3       0.006973  
4       0.007116

In [21]:
test_data = test_df['comment_text'].values
y_out = curr_best_sub.values[:,1:]
print(test_data[0])
print(y_out[:5])

Yo bitch Ja Rule is more succesful then you'll ever be whats up with you and hating you sad mofuckas...i should bitch slap ur pethedic white faces and get you to kiss my ass you guys sicken me. Ja rule is about pride in da music man. dont diss that shit on him. and nothin is wrong bein like tupac he was a brother too...fuckin white boys get things right next time.,
[[0.9815181734597362 0.35512813254770986 0.9613652944987894
  0.13540147289125098 0.906110645395769 0.4104500336545279]
 [0.008279015338395269 0.007032990104604411 0.007163288556332428
  0.006914050028604988 0.007326317659946539 0.007096527737436245]
 [0.010244547333057494 0.007199979368604889 0.00824177873749455
  0.0069714583491346455 0.007609482264164149 0.007178738473849276]
 [0.0071628125547653345 0.006918283240007093 0.0070627949437709015
  0.006965216438628063 0.00711456794393114 0.006972625016339156]
 [0.011147975815093528 0.006964625418279027 0.007655919311470762
  0.006929617561573975 0.007924036345632074 0.0071161

In [22]:
for idx,t in enumerate(test_data):
    for k in low_correct_dict:
        if k.lower() in t.lower():
            print(t)
            old_y = y_out[idx].copy()
            new_res = low_correct_dict[k]
            changed_flag = False
            for j in range(6):
                if new_res[j] == 1:
                    if y_out[idx][j] > 0.5: # update
                        changed_flag = True
                        y_out[idx][j] = min(0.9999,y_out[idx][j]*1.2)
            if changed_flag:
                print(old_y)
                print(y_out[idx])
            print('--------------------')

FUCK YOU YOU LIKE ANGELIQUE CARRINGTON AND TAMARA HARRINGTON??????FUCK YOU ASSHOLE!!!!!!
[0.9857469402052436 0.5861367262113074 0.982196866777492
 0.010838727774883402 0.949171861749894 0.03919461292472297]
[0.9999 0.5861367262113074 0.9999 0.010838727774883402 0.949171861749894
 0.03919461292472297]
--------------------
How does it feel now you faggot
[0.9676266913284052 0.07051252838285113 0.7584803188271407
 0.009066295252221931 0.7926899962939734 0.338390802987706]
[0.9999 0.07051252838285113 0.7584803188271407 0.009066295252221931
 0.7926899962939734 0.338390802987706]
--------------------
" 

 To the person who said: ""WHAT THE FUCK BITCH, STOP BLOCKINMG ME OR ILL KICK YOUR FUCK ASS!!!!!!!!!!!!!!!!!!!!!!!!!!!!'"" - Never say that to an admin. You need to learn respect for others.  "
[0.9819004601196404 0.3968641040799028 0.975685201529169
 0.12357055763800755 0.8743851778557116 0.03012516386586568]
[0.9999 0.3968641040799028 0.9999 0.12357055763800755 0.9999
 0.03012516386586568]

Philoso    fuck bitches get money phy
[0.9840131305372344 0.4160857038005662 0.981845057875841
 0.008369559677212174 0.9166394825895736 0.13298214405888908]
[0.9999 0.4160857038005662 0.9999 0.008369559677212174 0.9999
 0.13298214405888908]
--------------------
==buzon23== 
 You are a son of bitch!!!
[0.9821016427481568 0.2859512347913872 0.9600246018330528
 0.009894306569467552 0.9353474715495624 0.04226894343667728]
[0.9999 0.2859512347913872 0.9999 0.009894306569467552 0.9353474715495624
 0.04226894343667728]
--------------------
fuck fuck fuck fuck fuck
[0.9846322388508228 0.5476110242589293 0.9828377603482074
 0.007917201247318458 0.6701264467966657 0.02488515474338904]
[0.9999 0.5476110242589293 0.9999 0.007917201247318458 0.6701264467966657
 0.02488515474338904]
--------------------
fuck off you dickhead and what kind of name is squeakbox anyway,change it fast or you die.
[0.9841257187330694 0.4036551222937528 0.9783286545105564
 0.3268438110842742 0.9260925964675416 0.035305298

== fuck you == 

 fuck you asshole..freedom of speech bitch
[0.9857076564835608 0.6292787509843211 0.9837444739629976
 0.009840657473507259 0.9593709938094188 0.07032299301845696]
[0.9999 0.6292787509843211 0.9999 0.009840657473507259 0.9593709938094188
 0.07032299301845696]
--------------------
==THIS SCHOOL ROCKS== 

 HI, /b/ILLY MAYS HERE WITH ANOTHER FANTASTIC PRODUCT. ARE YOU TIRED OF GOING TO A SHITTY HIGH SCHOOL? TIRED OF BEING PUSHED AROUND BY BULLIES? DO YOU WANT TO GO TO A SCHOOL WHERE EVERYONE'S AS BIG A PUSSY AS YOU? OF COARSE YOU DO YOU SHITFUCK, THAT'S WHY YOU GOTTA TRY MY NEWEST PRODUCT, IT'S CALLED SOUTH PASADENA HIGH SCHOOL AND IT'S GUNNA FIX ALL YOUR PANSY-ASS PROBLEMS. IT'S ALL IN THE SOUTH PASADENIC G12 TECHNOLOGY, WHICH TAKES YOU THROUGH 4 YEARS OF PURE HOMOSEXUAL DELIGHT. WHAT YOU'RE GONNA DO IS GO DOWN TO SOUTH PASADENA, ENTER THROUGH THESE DOORS AND KABOOM BABY, YOU'RE IN. OH NO, SOMEONES SPILLED SOME SHIT ALL OVER THE CAFETERIA  	 LES, OH NO, THAT'S OKAY, THE S

==You Cunt == 
 Go fuck yourself you piece of shit. Don't make me tea beg your mama you faggot!!!
[0.986250680244498 0.6343845897034219 0.9816705912380492
 0.024705605443264802 0.9292421163286404 0.4836923735934053]
[0.9999 0.6343845897034219 0.9816705912380492 0.024705605443264802
 0.9292421163286404 0.4836923735934053]
--------------------
== Da Realist (Roc) == 

 Da Realist is one gay ass nigga Name Roc who spends his time on facebook trying to fuck niggas....he is a child molester an loves underage Boys... 

 He Lives in statesboro,ga 

 links to his page 

     * Log On With Caution* 

 http://www.facebook.com/profile.php?id=540150553#!/profile.php?id=100000598720561 

 for any gay dude that wanna talk to him get at him his number 912 618 3771 

 Hehe you my boi doe man LMAO srry
[0.9656354926092324 0.176533921430457 0.8874353674802917
 0.013570952445216168 0.783722590522141 0.7343290503380877]
[0.9999 0.176533921430457 0.8874353674802917 0.013570952445216168
 0.783722590522141 0

a little bitch who has called me a domestic terrorist. so do something about it cocksucker. you know where i live. your bitches have been here before.FUCK OFF YOU LITTLE ANAL BITCH
[0.9853754029613064 0.4692095483444754 0.9771214077306758
 0.02240124906386208 0.9498713921845736 0.15982456082315438]
[0.9999 0.4692095483444754 0.9771214077306758 0.02240124906386208
 0.9498713921845736 0.15982456082315438]
--------------------
talk]])  

 fuck fuck fuckety fuck fuck!
[0.9839730323661716 0.42069609844539535 0.9822904510655348
 0.0077033816343323345 0.6232712646249792 0.022311138614644687]
[0.9999 0.42069609844539535 0.9999 0.0077033816343323345
 0.6232712646249792 0.022311138614644687]
--------------------
" 
 :It's in the history. And if you think ""fuck off you cunt"" is an appropriate use of a talk page, you're in the wrong place. ''''''  "
[0.977258724996698 0.10534510920000008 0.9447501293373654
 0.00783691780442923 0.6607801874185812 0.015061259009557931]
[0.9999 0.10534510920000008 

== Bitcoin deletion == 

 WTF!! What if your fucking problem! 

 I spent a week on that article you piece of shit! That was an essay I was writing for myself to eventually publish on the net. You could have at least given me a day to copy the text. 

 Fuck you asshole.
[0.9803684052872292 0.2199143379625509 0.9682452061819796
 0.009849493869814357 0.9001056740088138 0.021888521724075998]
[0.9999 0.2199143379625509 0.9999 0.009849493869814357 0.9001056740088138
 0.021888521724075998]
--------------------
This one is for the boys with the booming system 
 Top down, AC with the cooling system 
 When he come up in the club, he be blazin' up 
 Got stacks on deck like he savin' up 

 And he ill, he real, he might got a deal 
 He pop bottles and he got the right kind of bill 
 He cold, he dope, he might sell coke 
 He always in the air, but he never fly coach 
 He a motherfucking trip, trip, sailor of the ship, ship 
 When he make it drip, drip kiss him on the lip, lip 
 That's the kind of du

::::::::He didn't retire, he was blocked for being incivil then replacing peoples user pages with ==White Trash== Fuck off you white piece of trash. Fucking wiggers. Go and fuck a Jew, Jew raper.. And still has been doing these antics, e.g. Blow me bitch I'll rape your mom. I'll tear her cunt apart. And then I'll stick a red hot poker up her ass AND yours. Hahaha you'll never ban me. Its said to see you try so hard to get me banned. You must really hate me. I appreciate it. You'll never find me. And I'll just keep on editing. Take that and shove it up your hole!.
[0.9815428501959848 0.4019693407455904 0.9559978849115538
 0.4267952920355962 0.9030426141553882 0.7594038493892151]
[0.9999 0.4019693407455904 0.9559978849115538 0.4267952920355962
 0.9030426141553882 0.7594038493892151]
--------------------
fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck mother fuck fuck me
[0.9845613519561636 0.6255579338113157 0.981969077906991
 0.008472351433507826 0.7839854311163045 0.02601215353013979

FUCKIDY FUCK FUCK FUCK!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[0.985091581479098 0.5754633101806909 0.9830909017685788
 0.008347157883993959 0.6950610155686556 0.02753216720502629]
[0.9999 0.5754633101806909 0.9999 0.008347157883993959 0.6950610155686556
 0.02753216720502629]
--------------------
, 27 January 2010 (UTC) 
 ::::::H C P what I'm reppin mane 
 If you ain't bout that better get the stepping mane 
 H C P what I'm reppin mane 
 If you ain't bout that betta get the stepping mane 
 H C P what I'm reppin mane 
 If you ain't bout that betta get the stepping mane 
 H C P what I'm reppin mane 
 If you ain't bout that betta get the stepping mane 

 [Verse 1] 
 Now I'm a tell you off top shit gone get a little drastic 
 Frayser come around its a wrap like plastic 
 Never punked out or pushed around like a basket 
 Keep yo lips zipped or you'll be next wit yo ass kick 
 Make it stick and move in and out like mash it 
 Handle that get the check, hit the bank, cash it 
 Niggas talking shit don't y

Fuck off you Chameleons-loving cunt. 
 :
[0.9838365812387212 0.4396140511391309 0.9814558578928332
 0.008687542630854727 0.9290245219468672 0.1147582970444567]
[0.9999 0.4396140511391309 0.9814558578928332 0.008687542630854727
 0.9290245219468672 0.1147582970444567]
--------------------
" 

 ""Hit 'Em Up"" 

 [Tupac] 

 I ain't got no mutha fuckin friends 
 Thats why I fucked your bitch 
 You fat mutha-fucka {Take Money} 
 West Side 
 Bad Boy Killers {Take Money} 
 You know who the realist is 
 niggas we bring it to {Take Money} 
 (ha ha, that's alright) 

 First off, fuck your bitch 
 And the click you claim 
 West side when we ride 
 Come equipped with game 
 You claim to be a playa 
 But, I fucked your wife 
 We bust on Bad Boys 
 niggas fuck for Life 
 Plus Puffy tryin' to see me weak 
 Hearts I rip 
 Biggie Smalls and Junior Mafia 
 Some mark ass bitches 
 We keep on coming 
 While we running for yah jewels 
 Steady gunning 
 Keep on busting at them fools 
 You know the rules 
 Li

== Oi Dickhead == 
 Get the fuck off my talk page, or else I'm gonna come down and fuck u so hard that you'll never come on my talk page again. OK? Go fuck off you dick-sagging wanking rapist.
[0.985185506615043 0.4841665954453696 0.9801918013995272
 0.05496380646827708 0.9311378129519968 0.06946760932784414]
[0.9999 0.4841665954453696 0.9801918013995272 0.05496380646827708
 0.9311378129519968 0.06946760932784414]
--------------------
Why did you block my friend, all he was doing was sharing his opinion about HOW GAY YOU ARE!!! All he did was comment about how you have NO FREAKING LIFE, AND HOW YOU LIVE WITH YOUR MOM, AND HOW YOU SUCK BEYOND BELIEF!!! 
 THAT WAS ALL...BUT YA KNOW WHAT...I THINK IM GONNA HAVE TO AGREE WITH HIM...YOU SUCK!!! HE IS DEFINATELY RIGHT, YOU ARE GAY, AND A QUEER!!! GO MAKE OUT WITH YOUR MOM, YA BIG PORKER!!!! 
 I HATE YOU ANTANDRUS...WTF KIND OF A NAME IS ANTANDRUS...I MEAN I COULD COME UP WITH 10 BETTER NAMES RIGHT OFF THE TOP OF MY HEAD...lets see.  Well its

[0.9847932083649088 0.5827790475973605 0.9821603632376084
 0.008669907481893072 0.8215663075602112 0.1182682949491455]
[0.9999 0.5827790475973605 0.9999 0.008669907481893072 0.8215663075602112
 0.1182682949491455]
--------------------
== Edit request on 14 January 2013 == 

  

  

    
 Cheef keef is a bitch ass dude. He is not about that life and hes a hoe ass dude. He didnt kill little Jojo cause he a scared ass hoe, fuck you. you claim you a G and a blood. You stil a fucking hoe. When My Niggas catch you its sad cause you a bitch. Your mom going to get murderd and your daddy going to get raped
[0.9851101693968564 0.4614016032018942 0.9649507246102386
 0.4766641832884434 0.9378373200316876 0.5711368514824787]
[0.9999 0.4614016032018942 0.9649507246102386 0.4766641832884434
 0.9378373200316876 0.5711368514824787]
--------------------
Hey! Fuck you; you stupid prick. This is a shared IP and I don't need your queer recommendations on how to use the sandbox. I use Wikipedia frequently a

== Thanks for deleting the article motherfucker == 

 Fuck you asshole.
[0.9848262480196124 0.3586406384074952 0.9794844506573088
 0.009244432135714364 0.9286836474586616 0.021044573053055373]
[0.9999 0.3586406384074952 0.9999 0.009244432135714364 0.9286836474586616
 0.021044573053055373]
--------------------
I think you faggots should stop trying to be the first one to put bullshit information on here, and instead wait for the news organizations to get their facts straight.
[0.94444075396328 0.034949647896492214 0.7699920859865015
 0.009001602930139869 0.6264546202519481 0.1869723422836034]
[0.9999 0.034949647896492214 0.7699920859865015 0.009001602930139869
 0.6264546202519481 0.1869723422836034]
--------------------
semen fuck bitches ass motherfucker
[0.9853738464226948 0.5921279866855091 0.9832787097063688
 0.011943054129718831 0.9434778766112828 0.11523503721483795]
[0.9999 0.5921279866855091 0.9999 0.011943054129718831 0.9999
 0.11523503721483795]
--------------------
EAT SHIT A

In [23]:
sub = curr_best_sub.copy()
sub[['toxic','severe_toxic','obscene','threat','insult','identity_hate']] = y_out
sub.to_csv('../results/key_word_update.csv.gz',index=False, compression='gzip')
sub.head()  # still PUB 9872, no improve

id     toxic  severe_toxic   obscene    threat    insult  \
0  00001cee341fdb12  0.981518      0.355128  0.961365  0.135401  0.906111   
1  0000247867823ef7  0.008279      0.007033  0.007163  0.006914  0.007326   
2  00013b17ad220c46  0.010245      0.007200  0.008242  0.006971  0.007609   
3  00017563c3f7919a  0.007163      0.006918  0.007063  0.006965  0.007115   
4  00017695ad8997eb  0.011148      0.006965  0.007656  0.006930  0.007924   

   identity_hate  
0       0.410450  
1       0.007097  
2       0.007179  
3       0.006973  
4       0.007116