In [51]:
import pickle
import pandas as pd

train_x,test_x = pickle.load(open('../features/cnn_1_feat.pkl','rb'))
train = pd.read_csv("../input/train.csv")

list_classes = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]
y = train[list_classes].values
print(train_x.shape,y.shape)

(95851, 6) (95851, 6)


In [52]:
train.head()

id                                       comment_text  toxic  \
0  22256635  Nonsense?  kiss off, geek. what I said is true...      1   
1  27450690  "\n\n Please do not vandalize pages, as you di...      0   
2  54037174  "\n\n ""Points of interest"" \n\nI removed the...      0   
3  77493077  Asking some his nationality is a Racial offenc...      0   
4  79357270  The reader here is not going by my say so for ...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [53]:
train_x[:10].round(3)

array([[ 0.22 ,  0.001,  0.017,  0.002,  0.038,  0.006],
       [ 0.006,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.003,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.003,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.004,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.041,  0.   ,  0.006,  0.001,  0.005,  0.003],
       [ 0.026,  0.   ,  0.002,  0.   ,  0.003,  0.001],
       [ 0.052,  0.   ,  0.002,  0.   ,  0.007,  0.002],
       [ 0.018,  0.   ,  0.002,  0.   ,  0.002,  0.001],
       [ 0.03 ,  0.   ,  0.002,  0.   ,  0.003,  0.002]])

In [54]:
y[:10]

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [55]:
test_x[:5].round(3)

array([[ 0.025,  0.   ,  0.004,  0.001,  0.005,  0.002],
       [ 0.001,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.021,  0.   ,  0.005,  0.001,  0.004,  0.002],
       [ 0.006,  0.   ,  0.001,  0.   ,  0.001,  0.   ]])

In [56]:
from sklearn.metrics import log_loss,accuracy_score
import numpy as np
def eval_val(y,train_x):
    res = 0
    acc_res = 0
    for i in range(6):
        curr_loss = log_loss(y[:,i],train_x[:,i])
        acc = accuracy_score(y[:,i],train_x[:,i].round())
        print(i,curr_loss,acc)
        res += curr_loss
        acc_res += acc
    print('final',res/6, acc_res/6)

eval_val(y,train_x)

0 0.114356459409 0.958237264087
1 0.0240665935598 0.99013051507
2 0.0580006967855 0.97838311546
3 0.0152731398063 0.996817977903
4 0.0720637702078 0.970589769538
5 0.0311482905998 0.991507652502
final 0.0524848250613 0.980944382427
