In [1]:
# ref: https://www.kaggle.com/tilii7/tuned-logreg-oof-files

import numpy as np
import pandas as pd
import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from scipy.sparse import hstack
from sklearn.metrics import log_loss, matthews_corrcoef, roc_auc_score

class_names = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

train = pd.read_csv('../input/train.csv').fillna(' ')
test = pd.read_csv('../input/test.csv').fillna(' ')
tr_ids = train[['id']]
train[class_names] = train[class_names].astype(np.int8)
target = train[class_names]

print(' Cleaning ...')
# PREPROCESSING PART
repl = {
    "yay!": " good ",
    "yay": " good ",
    "yaay": " good ",
    "yaaay": " good ",
    "yaaaay": " good ",
    "yaaaaay": " good ",
    ":/": " bad ",
    ":&gt;": " sad ",
    ":')": " sad ",
    ":-(": " frown ",
    ":(": " frown ",
    ":s": " frown ",
    ":-s": " frown ",
    "&lt;3": " heart ",
    ":d": " smile ",
    ":p": " smile ",
    ":dd": " smile ",
    "8)": " smile ",
    ":-)": " smile ",
    ":)": " smile ",
    ";)": " smile ",
    "(-:": " smile ",
    "(:": " smile ",
    ":/": " worry ",
    ":&gt;": " angry ",
    ":')": " sad ",
    ":-(": " sad ",
    ":(": " sad ",
    ":s": " sad ",
    ":-s": " sad ",
    r"\br\b": "are",
    r"\bu\b": "you",
    r"\bhaha\b": "ha",
    r"\bhahaha\b": "ha",
    r"\bdon't\b": "do not",
    r"\bdoesn't\b": "does not",
    r"\bdidn't\b": "did not",
    r"\bhasn't\b": "has not",
    r"\bhaven't\b": "have not",
    r"\bhadn't\b": "had not",
    r"\bwon't\b": "will not",
    r"\bwouldn't\b": "would not",
    r"\bcan't\b": "can not",
    r"\bcannot\b": "can not",
    r"\bi'm\b": "i am",
    "m": "am",
    "r": "are",
    "u": "you",
    "haha": "ha",
    "hahaha": "ha",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "won't": "will not",
    "wouldn't": "would not",
    "can't": "can not",
    "cannot": "can not",
    "i'm": "i am",
    "m": "am",
    "i'll" : "i will",
    "its" : "it is",
    "it's" : "it is",
    "'s" : " is",
    "that's" : "that is",
    "weren't" : "were not",
}

keys = [i for i in repl.keys()]

new_train_data = []
new_test_data = []
ltr = train["comment_text"].tolist()
lte = test["comment_text"].tolist()
for i in ltr:
    arr = str(i).split()
    xx = ""
    for j in arr:
        j = str(j).lower()
        if j[:4] == 'http' or j[:3] == 'www':
            continue
        if j in keys:
            # print("inn")
            j = repl[j]
        xx += j + " "
    new_train_data.append(xx)
for i in lte:
    arr = str(i).split()
    xx = ""
    for j in arr:
        j = str(j).lower()
        if j[:4] == 'http' or j[:3] == 'www':
            continue
        if j in keys:
            # print("inn")
            j = repl[j]
        xx += j + " "
    new_test_data.append(xx)
train["new_comment_text"] = new_train_data
test["new_comment_text"] = new_test_data

trate = train["new_comment_text"].tolist()
tete = test["new_comment_text"].tolist()
for i, c in enumerate(trate):
    trate[i] = re.sub('[^a-zA-Z ?!]+', '', str(trate[i]).lower())
for i, c in enumerate(tete):
    tete[i] = re.sub('[^a-zA-Z ?!]+', '', tete[i])
train["comment_text"] = trate
test["comment_text"] = tete
del trate, tete
train.drop(["new_comment_text"], axis=1, inplace=True)
test.drop(["new_comment_text"], axis=1, inplace=True)

train_text = train['comment_text']
test_text = test['comment_text']
all_text = pd.concat([train_text, test_text])

 Cleaning ...


In [2]:
train.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  explanation why the edits made under my userna...      0   
1  000103f0d9cfb60f  daww! he matches this background colour i am s...      0   
2  000113f07ec002fd  hey man i am really not trying to edit war it ...      0   
3  0001b41b1c6bb37e   more i can not make any real suggestions on i...      0   
4  0001d958c54c6e35  you sir are my hero any chance you remember wh...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [3]:
test.head()

id                                       comment_text
0  00001cee341fdb12  yo bitch ja rule is more succesful then youll ...
1  0000247867823ef7          from rfc  the title is fine as it is imo 
2  00013b17ad220c46               sources   zawe ashton on lapland    
3  00017563c3f7919a  if you have a look back at the source the info...
4  00017695ad8997eb         i do not anonymously edit articles at all

In [4]:
print(' Part 1/2 of vectorizing ...')
word_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    strip_accents='unicode',
    analyzer='word',
    token_pattern=r'\w{1,}',
    stop_words='english',
    ngram_range=(1, 1),
    max_features=10000)
word_vectorizer.fit(all_text)
train_word_features = word_vectorizer.transform(train_text)
test_word_features = word_vectorizer.transform(test_text)

print(' Part 2/2 of vectorizing ...')
char_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    strip_accents='unicode',
    analyzer='char',
    stop_words='english',
    ngram_range=(2, 6),
    max_features=50000)
char_vectorizer.fit(all_text)
train_char_features = char_vectorizer.transform(train_text)
test_char_features = char_vectorizer.transform(test_text)

train_features = hstack([train_char_features, train_word_features]).tocsr()
test_features = hstack([test_char_features, test_word_features]).tocsr()
print(train_features.shape,test_features.shape)

 Part 1/2 of vectorizing ...
 Part 2/2 of vectorizing ...
(159571, 60000) (153164, 60000)


In [5]:
target = target.values
print(target[:5])

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [8]:
def kf_train(k=5):
    all_parameters = {
                  'C'             : [1.048113, 0.1930, 0.596362, 0.25595, 0.449843, 0.25595],
                  'tol'           : [0.1, 0.1, 0.046416, 0.0215443, 0.1, 0.01],
                  'solver'        : ['lbfgs', 'newton-cg', 'lbfgs', 'newton-cg', 'newton-cg', 'lbfgs'],
                  'fit_intercept' : [True, True, True, True, True, True],
                  'penalty'       : ['l2', 'l2', 'l2', 'l2', 'l2', 'l2'],
                  'class_weight'  : [None, 'balanced', 'balanced', 'balanced', 'balanced', 'balanced'],
    }
    skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=1001)
    train_pred, test_pred = np.zeros((159571,6)),np.zeros((153164,6))
    for j in range(6):
        fold_idx = 0
        for train_index, test_index in skf.split(train_features,target[:,j]):
            # model
            model = LogisticRegression(
                C=all_parameters['C'][j],
                max_iter=200,
                tol=all_parameters['tol'][j],
                solver=all_parameters['solver'][j],
                fit_intercept=all_parameters['fit_intercept'][j],
                penalty=all_parameters['penalty'][j],
                dual=False,
                class_weight=all_parameters['class_weight'][j],
                verbose=0)
            
            # data
            curr_x,curr_y = train_features[train_index],target[train_index]
            hold_out_x,hold_out_y = train_features[test_index],target[test_index]
            
            # train
            model.fit(curr_x, curr_y[:,j])
            hold_out_pred = model.predict_proba(hold_out_x)
            curr_train_pred = model.predict_proba(curr_x)
            print(fold_idx,log_loss(hold_out_y[:,j],hold_out_pred),log_loss(curr_y[:,j],curr_train_pred))
            fold_idx += 1
            
            train_pred[test_index,j] = list(hold_out_pred[:,1].flatten())
            y_test = model.predict_proba(test_features)[:,1]
            test_pred[:,j] += y_test
        print('=========',class_names[j])
    test_pred = test_pred/k
    return train_pred, test_pred

train_pred,test_pred = kf_train(10)

0 0.10421944051444547 0.07736698901708022
1 0.10094516374483271 0.07768756315928728
2 0.09689469756724278 0.07806437054899934
3 0.09863308331991873 0.07785983306094772
4 0.10200903756054049 0.07746123913080742
5 0.09928556346338296 0.07778067034807377
6 0.10035638549797365 0.07772664411163223
7 0.09699550067162133 0.07807298499142155
8 0.09727854776595017 0.077957548997523
9 0.09894633549179196 0.07788655447932341
========= toxic
0 0.09432299978965594 0.09105163845294309
1 0.09404911480539416 0.09225918670048783
2 0.09150205475862452 0.09317590636753048
3 0.09802411240684075 0.09169241190021024
4 0.09031785302741922 0.09219540682696005
5 0.0989825810352689 0.09226142402206906
6 0.10043048350952256 0.09245957370430298
7 0.09407353583345726 0.09202573660552242
8 0.10018145114161303 0.09083473035890431
9 0.09717285384762389 0.09232136011437317
========= severe_toxic
0 0.09970445825599546 0.08304722684407272
1 0.09437409076292244 0.08339776929584362
2 0.09976100561542844 0.0836491430926247

In [9]:
import pickle
with open('../features/tilli_lr_feat.pkl','wb') as fout:
    pickle.dump([train_pred,test_pred],fout)
print(test_pred[:5])

[[0.99982861 0.94638479 0.99998611 0.58520974 0.99886107 0.94219621]
 [0.00392937 0.01838111 0.00370642 0.00385484 0.03252907 0.03356666]
 [0.00698681 0.01141339 0.019616   0.00381293 0.02736875 0.02219025]
 [0.00260546 0.01794668 0.0056303  0.00566862 0.00931623 0.00319148]
 [0.0132848  0.01632966 0.03347964 0.00568871 0.02679658 0.01133338]]
